### ISSUE TITLE
mkdir /storage/build results in error on windows 

### ISSUE THREAD

**Issue by benedictgeek** [niiknow/anx-api-proxy#1]
While running app:pacakage, the build process stops at 

mkdir /storage/build
The syntax of the command is incorrect.

I am on windows, what can I do?

**Comment by noogen** [comment]
I originally plan to output multiple files and that's why I needed to put it into a folder, hence `storage/build`.   I've made the change to composer script to simply output `dist.zip` into the root folder now so `mkdir /storage/build` has been removed.

**Comment by noogen** [comment]
Close due to inactivity.
